### ISSUE TITLE
Design change

### ISSUE THREAD

**Issue by lordgabber** [swetorrentking/rartracker#11]
Hello comrade!
I want to ask, how is design is changed?
I want make some redesign in my future project :dancers:

**Comment by swetorrentking** [comment]
First off. The site is based on Bootstrap CSS. You can find another bootstrap theme online that you like and just add that. Custom overrides is in rartracker.css.

If you want to do more structural changes to the site. You can mostly do that in index.html and app/header/header.template.html which cointain the position of the menu, status box and search bar. The components can be moved around to other places.
