### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by Skruf90** [swetorrentking/rartracker#12]
Hi. Do you have any contact information - irc or something. I would like to discuss the process I'm going to do with adding i18n system to the source. Feel free to message me on Skype or email Pjoff90@gmail.com

**Comment by lordgabber** [comment]
Lets talk here! ;)

**Comment by swetorrentking** [comment]
torrentking@dukgo.com

https://duck.co/blog/post/2/using-pidgin-with-xmpp-jabber

**Comment by Skruf90** [comment]
Added you. My address is pjoff@duckgo.com

**Comment by Skruf90** [comment]
** pjoff@dukgo.com

**Comment by lordgabber** [comment]
Hi. This is the qmail-send program at flash.duckduckgo.com.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<torrentking@dukgo.com>:
Unable to open ./Mailbox: access denied. (#4.2.1)
I'm not going to try again; this message has been in the queue too long.

**Comment by conyum** [comment]
I've added you torrentking. I've some questions :)
