### ISSUE TITLE
Cannot login as admin

### ISSUE THREAD

**Issue by dxpsite** [swetorrentking/rartracker#13]
http://clip2net.com/clip/m179451/b78b6-clip-53kb.png?nocache=1

**Comment by swetorrentking** [comment]
Check the server response. There are some returning server error I think. Possible you haven't set up
mod_rewrite/allow override to get .htaccess working.

**Comment by dxpsite** [comment]
I was tested on nginx. Now start with apache on port 8012 and get error:  
`SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)`

add line in my.cnf 
```
socket=/var/run/mysqld/mysqld.sock
datadir=/var/lib/mysql
**bind-address = 127.0.0.1**
#log_bin=0
skip-network
skip-external-locking
```
then restart...

no changed..

**Comment by swetorrentking** [comment]
The error is server config, not a tracker issue.
