### ISSUE TITLE
Conflict AngularJs version when do the cmd : bower install

### ISSUE THREAD

**Issue by Dark-pho3nix** [swetorrentking/rartracker#18]
Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#1.4.x which resolved to 1.4.12 and is required by angular-chart.js#0.8.9
    2) angular#1.5.7 which resolved to 1.5.7 and is required by angular-cookies#1.5.7, angular-resource#1.5.7, angular-sanitize#1.5.7
    3) angular#>=1.2.26 <1.6 which resolved to 1.5.7 and is required by angular-translate#2.11.0, angular-translate#2.11.0
    4) angular#^1.0.8 which resolved to 1.5.7 and is required by angular-ui-router#0.3.1
    5) angular#~1.5.6 which resolved to 1.5.7 and is required by angular-tracker
    6) angular#>=1.4.0 which resolved to 1.5.7 and is required by angular-bootstrap#1.2.5

Thanks in advance.

**Comment by swetorrentking** [comment]
I'll fix this. In the meantime just choose the latest version, (2).

**Comment by Dark-pho3nix** [comment]
Thanks all is working :)

Another question, it's normal to don't have the url of the tracker when we want to upload ?

**Comment by lordgabber** [comment]
When you upload a torrent file, and then download for seeding, you automatically got annonser URL in your torrent.. When you create a torrent file, you can typy anything!
Hope Im correct!

**Comment by Dark-pho3nix** [comment]
Thanks lordgabber, that's right.
I will make a small modification to add the tracker url without the passkey :)

**Comment by swetorrentking** [comment]
Fixed
