### ISSUE TITLE
Seed not recognized

### ISSUE THREAD

**Issue by raphaeljorge** [swetorrentking/rartracker#19]
Hello, I have a problem in uploading, downloading and recognition seed.

After you finish configuring the tracker, I was testing the upload and download torrents, here came a doubt, what is the correct syntax for the url Announce? I'm using: http://myurl.com/tracker.php/passkey/announce

Testing with this url above I generated the torrent and I uploaded it immediately after I downloaded the torrent, but when I start the seed of even the tracker does not count and does not recognize that they have seed.

![Image](http://image.prntscr.com/image/330ef2e9e6cf4c798f68b9f563a05df7.png)

![Image](http://image.prntscr.com/image/53eb3d100933432ab106238dd3b886a2.png)

**Comment by swetorrentking** [comment]
What about tracker status in the client. The seeding bar looks red. Is it able to contact the tracker? Is it the correct url and port setup (Config.php) and is the port open?

**Comment by raphaeljorge** [comment]
Hey @swetorrentking the status is empty 
[Status](http://image.prntscr.com/image/2478ca9747b149bba240f33e728038f3.png)
It is only updating without changing the status.

Yes, the URL is correct, I need to open any port on the server? I opened TCP and UDP ports 1337 and 1338, to test, as seen in a file requesting the doors, but still does not work.

Currently open ports are: HTTP / 80, HTTPS / 443, SSH, 1337 and 1338

**Comment by swetorrentking** [comment]
The tracker update request is just a simple HTTP GET request you can do from your web browser to try it out. Like, https://yourtracker.org:1338/ should work. If it doesn't work check your web server config for ports/ssl and open ports.

Port 1338 is an SSL port as default.

**Comment by raphaeljorge** [comment]
I need to forward port 1337 and 1338 where? What I need port settings do?

**Comment by swetorrentking** [comment]
I'm talking about webserver (Apache) ports. You could make it easy and just remove :1337 and :1338 to use the default ports (80, 443) in Config.php. Just change and re-download torrents.

**Comment by Zezou** [comment]
You really an apache config file.

**Comment by Zezou** [comment]
I don't see any port numbers in the Config.php page

**Comment by swetorrentking** [comment]
If you want a different port for the tracker just add it:

const TRACKER_URL = "http://rartracker.org:5000";
