### ISSUE TITLE
Cannot login.

### ISSUE THREAD

**Issue by webzi** [swetorrentking/rartracker#2]
Got a problem when trying to login.

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /api/v1/auth was not found on this server.</p> <hr> <address>Apache/2.4.7 (Ubuntu) Server at 127.0.0.1 Port 80</address> </body></html>

But as I can see the api/v1 folder doest not exist. How to get it?

Thanks.

**Comment by webzi** [comment]
Okay.. Fixed the api issues.

But now when I try to login,this is what I get. https://i.gyazo.com/49b84c11386482e8f2e40184e88f7aba.png

**Comment by swetorrentking** [comment]
Use Chrome developer tool (or similiar) to inspect the server response. Here you should see what went wrong.

One common issue is PHP Notice or PHP Strict errors, which need to be turned off in php.ini.

**Comment by webzi** [comment]
Hi,

This is what I get when I press login.

TypeError: Cannot read property 'serverTime' of undefined
    at Object.u [as serverResponse] (app-dist.js:3)
    at e.get.b.data.a.addAlert.type (app-dist.js:2)
    at angular-resource.js:643
    at angular.js:14792
    at r.$eval (angular.js:16052)
    at r.$digest (angular.js:15870)
    at r.$apply (angular.js:16160)
    at g (angular.js:10589)
    at T (angular.js:10787)
    at XMLHttpRequest.w.onload (angular.js:10728)

**Comment by webzi** [comment]
Why did you close the issue?

**Comment by swetorrentking** [comment]
Have you checked for php errors or similiar in the AJAX server response?

**Comment by webzi** [comment]
Hi,

Yes i did check that - I can´t seem to find any errors.

**Comment by swetorrentking** [comment]
But what is the server response from the AJAX-request when you try to login? Is it valid json data? is it just blank? In that case it could be some php error that has been silenced if error reporting is off.

**Comment by lordgabber** [comment]
webzi can you contact me?

**Comment by webzi** [comment]
Sure. Where?

**Comment by lordgabber** [comment]
traxcock@gmail.com
