### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by georgee** [swetorrentking/rartracker#20]
Hi,so installed the rartracker but when i'm going to log in i'm getting this error `could not find driver`

how can i solve this?

**Comment by swetorrentking** [comment]
There isn't anything in rartracker called driver so this must be some server installation issue. Which logs are you referring to? Apache? Php? It could be the Mysql driver that is missing...

**Comment by georgee** [comment]
After a little bit of research i found that PDO php module cause this problem.Tried to add an extension to php.ini to solve this but i can't get it to work.I will try to install it on another vps to see if i can get it to work.

**Comment by georgee** [comment]
i installed it again and it worked.I dont know if this was the issue that cause it but i installed apache2 php5-fpm memcached first and then i installed the dependencies.
