### ISSUE TITLE
Where to define Category Icons?

### ISSUE THREAD

**Issue by Jypels** [swetorrentking/rartracker#21]
Hi, I have successfully created all of my custom categories and they are working perfectly except I am unable to find the code where I have to state the path for new category images?

I know the images are saved in /img/catergories but where can I state to which category each image belongs to? Is it in the DB or am I missing something?

Thank you for the awesome Tracker btw!

**Comment by swetorrentking** [comment]
All the category icons is a sprite "img/icons-sprite.png".

And they are defined in rartracker.css  row 393:
```
img.categoryImage.category1 {
	background-position: 0 -435px;
}
```

You can a site like http://spritegen.website-performance.org/ and upload your images to create a new sprite with css cordinates.

**Comment by Jypels** [comment]
Littererly  sat with this the whole day, and now I feel so stupid haha. You learn something new each day hey!

**Comment by swetorrentking** [comment]
It's recommended to use Chrome developer tools and just right click inspect the category icons and you'll see where the image are specified.
