### ISSUE TITLE
Error on installing latest commit

### ISSUE THREAD

**Issue by riverstore** [swetorrentking/rartracker#27]
Hi,
WHen try to install the latest commit, I got this error when run 
>npm run dist

Anyone know the problem please help me. Thanks a lot.

> rartracker@0.3.1 dist /var/www/html/rartracker
> gulp dist

[16:31:20] Using gulpfile /var/www/html/rartracker/gulpfile.js
[16:31:20] Starting 'lint'...
[16:31:20] Starting 'dist-html'...
[16:31:20] Starting 'libs'...
[16:31:20] Starting 'css'...
[16:31:20] Starting 'copy-fontawesome'...
[16:31:20] Finished 'copy-fontawesome' after 918 μs
[16:31:20] Finished 'libs' after 55 ms

/var/www/html/rartracker/node_modules/copy-dir/index.js:218
    var dirs = list.dirs.map(function(v) {
                   ^
TypeError: Cannot read property 'dirs' of undefined
    at /var/www/html/rartracker/node_modules/copy-dir/index.js:218:20
    at /var/www/html/rartracker/node_modules/copy-dir/index.js:21:21
    at Object.oncomplete (fs.js:107:15)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by swetorrentking** [comment]
1. Do you have bower_components/font-awesome ?
2. Try removing both "./" from row 93 in gulpfile.js    So just:
copydir('bower_components/font-awesome/fonts', 'fonts', function(err){

3. Which OS are you running?

**Comment by riverstore** [comment]
Hi,

I dont have bower_components/font-awesome, I manualy copy it from my old installed rartracker and it work. Is there other way to get it?

**Comment by swetorrentking** [comment]
When you run "npm install" bower install should be executed and fetch font-awsome.

**Comment by riverstore** [comment]
I run 
>npm install
but font-awsome don't appear :(

**Comment by softsimon** [comment]
Maybe you lack bower.
npm install -g bower

**Comment by swetorrentking** [comment]
Maybe you are missing bower.
npm install -g bower
npm install should run bower install as postinstall and font-awesome is in bower.json.

Just tried a clean install and it worked.
