### ISSUE TITLE
Tracker  send invalid data: .

### ISSUE THREAD

**Issue by lordgabber** [swetorrentking/rartracker#28]
Hello King!
I got this error (in Mtorrent), when download and start seeding torrent file: "Tracker sending invalid data: ."
What i make wrong? :/

**Comment by anhydro** [comment]
Have you attempted to load the same torrent file in another client?

**Comment by lordgabber** [comment]
Hello!
Yes i try Tixati also.
But it say: "Invalid reply. Retry x.x min"
Check screenshots please:
![tixati](https://cloud.githubusercontent.com/assets/16883492/17896346/015f8038-6959-11e6-8a4d-71fb2b755386.jpg)
![mtorrent](https://cloud.githubusercontent.com/assets/16883492/17896359/09f4733e-6959-11e6-8469-4d8b0235005c.jpg)

I google it, but cant find something working solution!
Hope you and developer can help with this trouble!

**Comment by swetorrentking** [comment]
Because tracker.php is outputting errors.

Go to yoursite.com/tracker.php and you might see which errors. Maybe the db connection doesn't work or other syntax/notice errors.

**Comment by lordgabber** [comment]
Well, I check this adress, but see only empty page in browser ;/

**Comment by swetorrentking** [comment]
If the page is blank, you have not configured PHP or the database connection correctly. I guess you are getting some error which is hidden by display_errors = off.

I am closing this issue since its related to web server and database setup.

**Comment by lordgabber** [comment]
Trouble was in firewall... Now is OK!

**Comment by Kongledyret** [comment]
I am using both port 80 and 443 for https. But still getting this error.
