### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by lordgabber** [swetorrentking/rartracker#29]
Hello guys!
Can you help me to change and add new categories?
Check the attached screenshot please.
And provide a full path to files.. in other topic i dont find two files..
Thx in advance.
![categories](https://cloud.githubusercontent.com/assets/16883492/17977527/c697b2e2-6afa-11e6-8ab1-ce6cb8cae7ce.jpg)

**Comment by swetorrentking** [comment]
First I recommend to check out the latest master where categories config have been updated.

Categories are changed and added in **app/app.config.js** for client side and **api/Config.php** for the serverside. 

Which categories to be displayed on which pages is configed in **torrents.routes.js**. P2P, 3D and those buttons are in torrents.template.html.

**Comment by lordgabber** [comment]
Thx for full answer, but what you mean "latest master"? What is it? :/

**Comment by lordgabber** [comment]
in api/Config.php i see only:
class Config {

	const NAME = "";
	const SITE_NAME = "";
	const SITE_URL = "";
	const SITE_MAIL = "";

	const SUGGESTION_FORUM_ID = 4;
	const POLLS_FORUM_ID = 3;
	const NEWS_FORUM_ID = 1;

	const DEFAULT_LANGUAGE = "en";
	public static $languages = ["en", "sv"];

	const TRACKER_URL = "";
    const TRACKER_URL_SSL = "";

	public static $userClasses = array(
		0 => "Extra",
		1 => "Actor",
		2 => "Movie star",
		3 => "Director",
		4 => "Producer",
		6 => "Uploader",
		7 => "VIP",
		8 => "Staff");

}

And dont see anything about Categories..

**Comment by swetorrentking** [comment]
Version 0.3.2 is now published from lastest master and categories are configured in Config.php since that version.

To download latest master just click clone or download -> save zip. But now the 0.3.2-release is the latest master.

**Comment by lordgabber** [comment]
I'm download and see the categoties in Config.php now.
But how to update my 0.3.1 to 0.3.2 version? Just copy this new file on app foldier via FTP?
Or I need to make something more?

**Comment by lordgabber** [comment]
Hi dude...
We try few hours to change this categories (we updated on 0.3.2), but its not changed anyway.
Finally we comment all lines but its available anyway... hm.. something strange.
Any ideas?

**Comment by RobinHoutevelts** [comment]
You have to run `npm run dist` after your changes.

**Comment by lordgabber** [comment]
Thx for your feedback, i try it today!

**Comment by lordgabber** [comment]
I try!
Something changed, something not.
And also brocken Request section:
![1](https://cloud.githubusercontent.com/assets/16883492/18134083/bdb757cc-6fa5-11e6-88c1-634b15b0c83f.jpg)

**Comment by RobinHoutevelts** [comment]
What errors does your browser's console log show?

**Comment by lordgabber** [comment]
And now, when i try upload i got this error:
![2](https://cloud.githubusercontent.com/assets/16883492/18136384/da9f8bc2-6fad-11e6-8e61-1cd08ebe997a.jpg)

**Comment by swetorrentking** [comment]
Check row 680 in Torrent.php which defines which categories are valid or not. It just checks for the least and the biggest categori ID.

**Comment by tuhinbhuiyan** [comment]
I am going through same problem. I am not familer with Node. I have setup this in linux environment but when I try to modify config.php and app.config.js using npm run watch and after npm run dist. Nothing is happening.

I run npm run watch first after editing file via notepad at root dir.
Watch notice the modifications then 
I press CTRL+Z and stop the process then I run at root dir again
npm run dist > it compiles the files. But no changes.

Any help please?.

![modifcation](https://cloud.githubusercontent.com/assets/12027872/21344199/bcf04cb0-c6c4-11e6-9c5d-1c0b0aaa1ac1.jpg)
