### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by lordgabber** [swetorrentking/rartracker#3]
Hello King!
How I can translate traker on English language from Swedish?

**Comment by swetorrentking** [comment]
Now there are no other way except asking a swedish person to go through every hardcoded string and translate them in both JS and PHP. I wish, in the future to get the opportunity to add i18n support with the possibility to use multiple languages with english and swedish as a standard choice.

**Comment by lordgabber** [comment]
I dont imagine how to do this.
And better I wait until you can add multilanuage in future.
I try to make tracker but I see thats to hard for me.
Your software more for pro coders, not for lame users like me ;)

**Comment by swetorrentking** [comment]
Translation i18n support is planned but no ETA.
