### ISSUE TITLE
Tracker status "Not Working" in qBittorent

### ISSUE THREAD

**Issue by RobinHoutevelts** [swetorrentking/rartracker#30]
Hi swetorrentking,

I finally got around [forking](https://github.com/RobinHoutevelts/rartracker/commits/master) to help with the PHP side of things.

However, I have little experience with setting up my own tracker and I'm running into some issues:

- In [/tracker.php](https://github.com/swetorrentking/rartracker/blob/fb89f32a9ae5dbbebb877968038dee5ca0e8d5c2/tracker.php#L3) you define the connection can only be made from `SERVER_PORT` **1337** or **1338**
  - Is there a specific reason port **80** isn't used?
- I've created a new user and uploaded a test-torrent. Is `http:/rartracker.dev/tracker.php/c42ac92186de41cacc9b291385ea62bd/announce` a valid URL? <sup>(I did edit my hosts file so rartracker.dev points to the server)</sup>
  - I'm asking because in my torrent-client <sup>(qBittorent)</sup> the tracker status is "**Not working**".
  - While debuging I tried [to log all relevant information](https://github.com/RobinHoutevelts/rartracker/commit/dbc7d3b741832bb422cff130c6ab3472eda3c096) ( `$_SERVER`, `$_REQUEST`, `$_GET`, `$_POST`) to get a better understanding of *what* the client sends, but it seems qBittorent isn't sending an http-request **at all**.
      - This is confirmed by the apache log file.
  - I [edited the port-check](https://github.com/RobinHoutevelts/rartracker/commit/8450659da3c64f21293f660ea365a1059942ab9b) because obviously my tracker-url uses port 80.

So is this an issue with me not understanding how clients communicate with trackers or could it be something else?

**Comment by RobinHoutevelts** [comment]
Nevermind, I'm an idiot ( qbitorrent isn't whitelisted and json_encode returned false ).

Works like a charm

**Comment by ihv40894** [comment]
How do you whitelist certain torrent clients?

**Comment by RobinHoutevelts** [comment]
In [/tracker.php](https://github.com/swetorrentking/rartracker/blob/fb89f32a9ae5dbbebb877968038dee5ca0e8d5c2/tracker.php#L7) you'll find the `$bannade` variable.

There you can add the *user agent* of a torrent client.

The user agent is stored with each request in `$_SERVER['HTTP_USER_AGENT']`

Here's a snippet I use to store all HTTP data in a log so I can analyse it later. I've put it at the top of `/tracker.php`

```php
<?php

$requestInfo = [
	'SERVER' => $_SERVER,
	'REQUEST' => $_REQUEST,
	'GET' => $_GET,
	'POST' => $_POST
];
$requestInfo = print_r($requestInfo, true);
$logFile = fopen('tracker.php.log', 'a');
fwrite($logFile, $requestInfo);
fclose($logFile);

```

The user agent of my qBittorent for example was `qBittorrent v3.3.4` and for my rtorrent client it was `rtorrent/0.9.2/0.13.2`.

**Comment by ihv40894** [comment]
I was under the impression that listing clients under the $bannade variable banned or blacklisted those clients. That is for whitelisting them? Have you tried deluge with this tracker?

**Comment by RobinHoutevelts** [comment]
Nope you are absolutely right.

I'm just being dumb today. Haven't tried deluge, will do so tomorrow.

Op 27-aug.-2016 8:16 PM schreef "ihv40894" <notifications@github.com>:

**Comment by ihv40894** [comment]
I still can't get mine to work with qBittorrent or Deluge, for some reason Transmission works.

http:/rartracker.dev/tracker.php/c42ac92186de41cacc9b291385ea62bd/announce

I was thinking it had something to do with client not knowing what to do with announce url after tracker.php but thats a total guess and have no actual proof.

http://stackoverflow.com/questions/14789604/directory-hierarchy-after-index-php

If you figure this out, please let me know. Thanks.

**Comment by RobinHoutevelts** [comment]
Here everything goes fine.

I create the torrent in qBittorent:
- tracker-url: rartracker.dev ( apparently it doesn't really matter what you use here as it get's overwritten )
- make sure you **untick** the "Start seeding after creation" box.
- Tick the box to make the torrent private

Then I upload the created torrent. After uploading I download the .torrent file from the site ( now the tracker-url is overwritten and my passkey is inserted ).

I load the .torrent file in qBittorent and it's stuck on **waiting**. This is normal because the files aren't at the expected location. ( Note: I don't have the "Not working" issue anymore )

I right-click on my torrent in qBittorent and choose "open destination folder"<sup>Could be named something else. I'm using a translated version of qBittorent</sup>
Then an explorer opens and I copy the files of my torrent into the opened directory and close it.

Finally I right-click on my torrent again and select "Force recheck". Now qBittorent sees I already have the files, checks the integrity and changes the status to **seeding**.

------

When I create a second account, download the torrent again and load it in another client everything works smoothly.

**Comment by ihv40894** [comment]
Hmm, I'm doing the same thing and mine is saying not working still. I wonder if its because it's behind cloudflare?

**Comment by RobinHoutevelts** [comment]
Are you seeing the qBittorent's http-requests in the apache log file?

**Comment by ihv40894** [comment]
No I don't see them in there at all. I see some old ones from transmission, but no qBittorrent.

**Comment by RobinHoutevelts** [comment]
When you open qBittorent and go to the "trackers" tab of your torrent. What URL do you see?

Example:
![screenshot](http://eih.bz/s1/qbittqmqj.png)

**Comment by ihv40894** [comment]
https://mysite.com/tracker.php/code/announce

status: not working
peers: 0
