### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Kongledyret** [swetorrentking/rartracker#33]
> rartracker@0.3.2 dist /var/www
> gulp dist

[19:09:38] Using gulpfile /var/www/gulpfile.js
[19:09:38] Starting 'lint'...
[19:09:38] Starting 'dist-html'...
[19:09:38] Starting 'libs'...
[19:09:38] Starting 'css'...
[19:09:38] Starting 'copy-fonts'...
[19:09:38] Finished 'copy-fonts' after 548 μs
[19:09:38] Finished 'libs' after 25 ms
/var/www/node_modules/copy-dir/index.js:218
    var dirs = list.dirs.map(function(v) {
                   ^

TypeError: Cannot read property 'dirs' of undefined
    at /var/www/node_modules/copy-dir/index.js:218:20
    at /var/www/node_modules/copy-dir/index.js:21:21
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by Kongledyret** [comment]
Fixed with manually running bower install.

**Comment by Kongledyret** [comment]
@swetorrentking 
![1ec9f163febdf74265bd42a93b387f50](https://cloud.githubusercontent.com/assets/21296300/18037635/83b74d8e-6d89-11e6-810e-639b82ceb02b.png)

Only file list after running: 

npm run watch, no display. 
Any ideas?

**Comment by swetorrentking** [comment]
What do you mean with no display?

**Comment by Kongledyret** [comment]
Figured it out, but do you have the re-write rule in nginx? 
Also what ports should be in the configs

**Comment by RobinHoutevelts** [comment]
Rewrite rules for nginx can be found here: https://github.com/swetorrentking/rartracker/issues/6#issuecomment-205821456

You'll need to listen on:
- Port 80 to reach the site
- Port 1337 so torrent clients can talk to the tracker
- Port 1338 ( with SSL enabled! ) so torrent clients can securely talk to the tracker
    - By default this option is enabled for every member

In [/api/Config.php](https://github.com/swetorrentking/rartracker/blob/ec0c5fa4208d5f63bbbb024b70e0473d6ebe61da/api/Config.php#L17) you'll need to edit `TRACKER_URL ` and `TRACKER_URL_SSL`.

```php
<?php
    const TRACKER_URL = "http://<hostname>:1337";
    const TRACKER_URL_SSL = "https://<hostname>:1338"
```

Obviously replace `<hostname>` with whatever hostname you use.

## Dev-hint

If you want to **force** regular HTTP tracker communication, just set `TRACKER_URL_SSL` to the same value as `TRACKER_URL`. This allows you to ignore messing with SSL for a while.

I do recommend setting up SSL if you're using this in production.

**Comment by Kongledyret** [comment]
Thx mate :)

**Comment by Kongledyret** [comment]
@swetorrentking @RobinHoutevelts  
![1ec9f163febdf74265bd42a93b387f50](https://cloud.githubusercontent.com/assets/21296300/18037635/83b74d8e-6d89-11e6-810e-639b82ceb02b.png)

Only file list after running: 

npm run watch:

`> rartracker@0.3.2 watch /var/www
> gulp watch

[20:25:18] Using gulpfile /var/www/gulpfile.js
[20:25:18] Starting 'dev-js'...
[20:25:18] Starting 'dev-html'...
[20:25:18] Starting 'libs'...
[20:25:18] Starting 'css'...
[20:25:18] Starting 'copy-fonts'...
[20:25:18] Finished 'copy-fonts' after 614 μs
[20:25:18] Finished 'css' after 151 ms
[20:25:18] Finished 'libs' after 173 ms
[20:25:18] Finished 'dev-html' after 257 ms
[20:25:18] Finished 'dev-js' after 285 ms
[20:25:18] Starting 'watch'...
[20:25:18] Finished 'watch' after 142 ms`

Only files list after running npm run dist and npm run watch.

**Comment by RobinHoutevelts** [comment]
Huh, where did your index.html file go to?

Could you upload your nginx vhost file to pastebin so we can take a look?
This is most likely just a bad setup. Any reason you refuse to use Apache2?

**Comment by Kongledyret** [comment]
I did the wrong thing. Installed apache2 instead. Now I get visual. 

When I log in I get:

"A server error has occured. This event has been logged."

When I try again i´m met with a blank page. 

Chrome dev-console points to: 

<hostname>/api/v1/status?timeSinceLastCheck=1

**Comment by RobinHoutevelts** [comment]
You sure you've enabled the *rewrite* module of Apache2?
`sudo a2enmod rewrite`

Also don't forget to change the `AllowOverride` directive in your **vhost** file or in `/etc/apache2/apache2.conf`. By default it might be set to `None`, change it to `All`.

```
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```

<sup>(Obviously change **/var/www/** to where your project is located)</sup>

Finally restart apache2
`sudo service apache2 restart`

**Comment by Kongledyret** [comment]
Solved, bad config on my end.

**Comment by k0nsl** [comment]
Which version of NPM are you guys using? I'm using `3.10.10` on Debian 8 and I am having a similar issue. See below:
```
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
/usr/lib
└── bower@1.8.0 

/usr/bin/gulp -> /usr/lib/node_modules/gulp-cli/bin/gulp.js
/usr/lib
└── gulp-cli@1.2.2 

npm WARN lifecycle rartracker@0.3.2~postinstall: cannot run in wd %s %s (wd=%s) rartracker@0.3.2 bower install /root/rartracker
npm WARN rartracker@0.3.2 No repository field.
npm WARN rartracker@0.3.2 No license field.

> rartracker@0.3.2 dist /root/rartracker
> gulp dist

[10:52:18] Using gulpfile ~/rartracker/gulpfile.js
[10:52:18] Starting 'lint'...
[10:52:18] Starting 'dist-html'...
[10:52:18] Starting 'libs'...
[10:52:18] Starting 'css'...
[10:52:18] Starting 'copy-fonts'...
[10:52:18] Finished 'copy-fonts' after 427 μs
[10:52:18] Finished 'libs' after 19 ms
/root/rartracker/node_modules/copy-dir/index.js:218
    var dirs = list.dirs.map(function(v) {
                   ^

TypeError: Cannot read property 'dirs' of undefined
    at /root/rartracker/node_modules/copy-dir/index.js:218:20
    at /root/rartracker/node_modules/copy-dir/index.js:21:21
    at FSReqWrap.oncomplete (fs.js:111:15)

npm ERR! Linux 4.4.21-1-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rartracker@0.3.2 dist: `gulp dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rartracker@0.3.2 dist script 'gulp dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rartracker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rartracker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rartracker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/rartracker/npm-debug.log
```
Any ideas as to what I am doing wrong, or hints on how to resolve this issue of mine?
