### ISSUE TITLE
Locales are not properly showing up on the /requests/add page.

### ISSUE THREAD

**Issue by ihv40894** [swetorrentking/rartracker#36]
The locales for REQUESTS.NAME_PLACEHOLDER and REQUESTS.COMMENT_PLACEHOLDER is not working correctly along with the buttons at the bottom.

This is happening on mysite.com/requests/add

**Comment by swetorrentking** [comment]
That page should work. So my guess is that the site is giving some other error causing this. Most likely have you changed categories and the page is trying to use categories not existing. Check in add-request.controller.js  in the this.imdbLessCategories-list.

**Comment by ihv40894** [comment]
That was the issue. Works perfect now. Thanks!
