### ISSUE TITLE
YouTube error

### ISSUE THREAD

**Issue by HDVinnie** [swetorrentking/rartracker#37]
When adding youtube to upload

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'youtube_id' in 'field list'/var/www/html/api/MovieData.php299

**Comment by swetorrentking** [comment]
Oh. the column is missing from the database import file.

You can run this SQL to create it manually:

    ALTER TABLE `imdbinfo` ADD `youtube_id` VARCHAR(15) NOT NULL AFTER `lastUpdated`;
