### ISSUE TITLE
BackEnd

### ISSUE THREAD

**Issue by lordgabber** [swetorrentking/rartracker#4]
Hello again King.
Where is back end?

**Comment by swetorrentking** [comment]
I don't fully understand the question. But the backend is what you find in the /api folder, which should be run on eg: Apache/PHP

**Comment by lordgabber** [comment]
For example I dont find where change categories, rename it.
I dont want tv-tracker, I want mp3 tracker with another caregories.
Also I dont find where register new admins.
And how to make it reg open.

**Comment by swetorrentking** [comment]
- Categories are set in app.config.js "categories". Code for handling different categories are handled in several places including app.routes.js, Torrent.php, upload.service.js
- Register new admins, the easiest way is to "invite" people from the built in System account and then change their status.
- There is no switch to enable open registration. The site is built on invites only. You'll have to modify the "create" method in User.php and/or create a permanent invite code.

**Comment by lordgabber** [comment]
Tnx mate for your answers!
Anyway its some hard fo me ;/
I'm waiting for new version (if it be).
Or looking for something more userfriendly ;)
Anyway thx for your product!!
