### ISSUE TITLE
Shoutbox

### ISSUE THREAD

**Issue by Kongledyret** [swetorrentking/rartracker#46]
Hi!

Possible to add a shoutbox?

**Comment by conyum** [comment]
of course.
you could rewright stuff like /log or /signup to get a working shoutbox.
it's all in there, if you know how to copy/paste. 

i'm soon done with mine, and will share it with torrentking then so he can add it here.

**Comment by Kongledyret** [comment]
Cool. I might need some help with something. Are you available on any services?

**Comment by conyum** [comment]
create an account on wire.com and i'll add you there :)

**Comment by Kongledyret** [comment]
Created! Same nick

**Comment by Kongledyret** [comment]
Did you find me?

**Comment by conyum** [comment]
sent a request :)
