### ISSUE TITLE
Need Coder

### ISSUE THREAD

**Issue by CoFix** [swetorrentking/rartracker#49]
Hi @swetorrentking,

I made my request list. Yes I know it is so much for one person but i think only first 10 list is hard and complex.

Others are should have on a torrent site..

My Offer is 2000 EURO. We can discuss about fee.

How you can trust me? We can use freelancer.com for payments.

For example one work after payment..

This offers for @swetorrentking but who one interesting pm me.

cooffix@gmail.com

Thank You.

**Comment by CoFix** [comment]
My Request List

1. Donations system must working full automatically. When users paid payment, they will get them gift automatically

Donations->              https://mega.nz/#!7IRGiKSQ!94bjmj4m3Dhb_KGI9mj4Q46UFUT1JFabYTb6LR5ZFVk
Signup Donations->       https://mega.nz/#!rdQGEYbJ!7TtrSSugAjvbbyWIdz_SykMn7K6JueeFYMOtAREJiJo

2. Signup with donations (Auto working)

3. IRC Channel Invite System
Irc Key Configurations Usercp Panel -> https://i.imgbox.com/agH2hxdB.png

4. IRC Torrent Announce System (New torrent will announce tracker irc channel)


5. Collage System

5. Hit&Runs System (And Hit&Runs showing userbar). People can delete them hnr torrents with bonus point or upload credit
6. Torrent Pretime
7. Advanced RSS System (Just Like Gazelle)

**Comment by CoFix** [comment]
My Request List

1. Donations system must working full automatically. When users paid payment, they will get them gift automatically
Donations->              https://mega.nz/#!7IRGiKSQ!94bjmj4m3Dhb_KGI9mj4Q46UFUT1JFabYTb6LR5ZFVk
Signup Donations->       https://mega.nz/#!rdQGEYbJ!7TtrSSugAjvbbyWIdz_SykMn7K6JueeFYMOtAREJiJo




2. IRC Channel Invite System
Irc Key Configurations Usercp Panel -> https://i.imgbox.com/agH2hxdB.png




3. IRC Torrent Announce System (New torrent will announce tracker irc channel)
https://i.imgbox.com/bnDMgDme.png




4. Collage System (JUST LIKE YOUR TORRENT-LIST SYSTEM)
Watch this ->  https://mega.nz/#!iIZ2BBID!Dx-4aYw7dI9Wr1dnvItSNqGh-JucJUEB-dKijE2jEEE
Browse page collections tags -> https://i.imgbox.com/PXGhJreV.png




5. Movies&TV and Subtitle System
Watch this ->  https://mega.nz/#!XRQHlYqZ!JLNe1Yz-lkbbHzYYGmfmDoAEp3XarC0KoxdKu71aAJU

**IF POSSIBLE BACKGROUND CAN HAVE FANART.TV IMAGES**  FANART.TV API SYSTEM
https://i.imgbox.com/wCzjN6gV.png
https://i.imgbox.com/6eT6wlSM.png
https://i.imgbox.com/bj5e9kIW.png




6. Hit and Runs on Statusbar and User Torrent Downloads History

**People can delete them hnr torrents with bonus point or upload credit**

https://beyondhd.xyz/myhistory.php
https://i.imgbox.com/7JTCDL7H.png
https://i.imgbox.com/5wOD17rz.png

Watch Video ->  https://mega.nz/#!WJoAzDoJ!ghCCZOyYhG4j2dwcfsGhnMKJXSArNaBsmXDWVrwJ7dk




7. GOG and STEAM API for ONLY Game Category
https://gogapidocs.readthedocs.io/en/latest/galaxy.html#api-gog-com
Steam: URL should be like http://store.steampowered.com/app/<app id>/
GOG: URL should be like https://www.gog.com/game/<game name>




8. Discogs api For Music Categories
https://www.discogs.com/forum/thread/234138




9. Advanced RSS System 
https://i.imgbox.com/VXatUUay.png
https://i.imgbox.com/6KVk9yKQ.png
https://i.imgbox.com/yeoOxhnR.png




10. More IMDB Info on Browse Page
Watch Video -> https://mega.nz/#!ycox1QSB!yX8sS3ClDnEfGqgoCCOHYT3kc6RSCciiSsk74HPd8KE




11. Top Torrents System
Watch Video -> https://mega.nz/#!HI4GWJhB!qKCGMpTbG6YHZjhx7bS6yzcKrzE_Qpw-HqWVSwXfHeI




12. Imdb Number,uploader, free, silver torrents search options in browse.page searchbox and Sorting by IMDB ID browse page
https://i.imgbox.com/0ZgQGGzj.png
https://i.imgbox.com/H86HfUgY.png




13. Whislist for Movies and TV Categories
https://i.imgbox.com/UrCzd4PL.png




14. User Status Active or Deactive
This options for admin panel. For example We are deleting users if doesnt login to tracker in 30days or 60days ..
But i dont want this. I dont care users login to tracker. What it is important for me? If he&she is seeding torrents it is ok for me. I dont want delete them about inactive. I hope you understand me.




15. Home Page Gold&Silver - Top Torrents - Seed Wanted Torrents - Dead Torrents - Latest Torrent Comments and Statistics
https://mega.nz/#!vA5jlKQT!505ENPEgtLrS8n7BiKsaAYzB5TQH-zEaMG60LA5_8CE




16. How many bonus points am I earning?
https://i.imgbox.com/2y2JqCLN.png




17. Torrents row system 
http://imgbox.com/nDAU1qSd
https://i.imgbox.com/1ZOPxoi2.png    (Usercp.php options)


https://i.imgbox.com/BNmxs9Hn.png 
https://i.imgbox.com/P0JiDVUI.png 
https://i.imgbox.com/YZEGJaNz.png
https://i.imgbox.com/FvozFyxR.png


OR This addon from Nexus (Chine Trackers) 
http://www.imagebam.com/image/279317530785661
http://www.imagebam.com/image/01bd44530785668
https://i.imgbox.com/Jo6bQfsD.png
http://www.imagebam.com/image/5113c2530785678




18. Freeleech Slots System




19. Torrent Bump System




20. User Download - Uplooad - PM - LeechWarn - Immunity System with Day Options
https://i.imgbox.com/4yKEgShB.png




21. Administrative User Search
https://i.imgbox.com/Bdd2kKUi.png




22. Connectable for statusbar and Admin Page Unconnectable Users



23. Mass Group PM - E-mail System and Mass Upload Credis - Bonuspoint - Freeleech Slots - Request Slots System



24. Watch User System For Staff




25. Inactive User List And Send Email System




26. All Torrent Client List. Ban options for Staff



27. Flood Control System




28. View Possible Cheats




29. Member User Promotion Settings (Automatically Working)




30. Shoutbox System (New Torrent, Forum and Torrent Post will announce in Shoutbox)




31. Torrent Screenshots in Upload Page




32. Torrent Mediainfo in Upload Page




33. Torrent Upcoming Encodes System




34. Torrent Gold - Silver - Bronze options with day - week and unlimited in Upload Page. If torrents have these options, it will show on Browse Page




35. Uploader Name in Browse Page




36. Torrent Comments Disable System




37. Forum Topic Poll Options




38. Torrent Pretime in Browse Page




39. Apply For Membership




40. Add User System For Staff



41. Active Users - Last 24 Hours Active Users - IRC Active Users for Home Page




42. IRC active Users will earn bonus points



43. More Stats for home page (User class, New Torrents etc..)



44. Give Bonus Points to uploader in torrent details page




45. Make Torrent Freelech with karma points in details page
https://i.imgbox.com/AZqqxlnp.png



46. Torrent Request Reseed System



47. Torrent Thanks and Vote System (Total vote will show on browse page)




48. Total Online and Share Ratio Time on Userdetails Page



49. Quick Login Link



50. Achievement or Badge System

**Comment by HDVinnie** [comment]
remove the direct link to BHD please

**Comment by CoFix** [comment]
Why? You are owner BHD? What is the problem about link?

**Comment by HDVinnie** [comment]
I am staff there and am creator/dev of Blu-Edition and UNIT3D. Again please remove the direct links! I don't care about the screenshots. But don't post links to other private trackers in general. The fact that you didn't blur usernames or anything in your screens is also not cool.

**Comment by mostvotedplaya** [comment]
For 2000 Euros you could easily have a site created from scratch that included all those features you mentioned, and if you can use freelancer for the payment why not post the project on there?

**Comment by CoFix** [comment]
Dont worry i did but cant find any good one.

**Comment by swetorrentking** [comment]
@CoFix I'll send you an email shortly ;-)

**Comment by CoFix** [comment]
@swetorrentking i am waiting :)

**Comment by CoFix** [comment]
Did you check your email spam folder? I am still waiting your email
