### ISSUE TITLE
wamp?

### ISSUE THREAD

**Issue by TheHatMan98** [swetorrentking/rartracker#50]
how do i install it in wamp?

**Comment by swetorrentking** [comment]
How detailed description do you need? Most of what is needed is already in the README guide.

**Comment by TheHatMan98** [comment]
what is nodejs? i uploaded the files and nothing happens!

**Comment by TheHatMan98** [comment]
fucking bad description!

**Comment by TheHatMan98** [comment]
and do i need nodejs?

**Comment by HDVinnie** [comment]
jeez take a chill pill.......if you don't know shit about coding ask nicely.

**Comment by TheHatMan98** [comment]
i did ask nicely

**Comment by TheHatMan98** [comment]
Still need help?
