### ISSUE TITLE
Rewrite rule for nginx

### ISSUE THREAD

**Issue by riverstore** [swetorrentking/rartracker#6]
Hi,

Can anyone please make rewrite rules for nginx? I tried some convert tools but no help.
Thanks a lot.

Regard.

**Comment by Satnet** [comment]
Or you could install Apache2 instead as that will work perfectly with this tracker software...

**Comment by dxpsite** [comment]
# nginx configuration 
location / { try_files $uri /index.html;}
location ~ .*/img { } 
location ~ .*/phpMyAdmin { } 
location ~ \.(html)$ { } 
location /api { rewrite ^/api/v1/(.*)$ /api/api-v1.php?url=$1 break; }
