### ISSUE TITLE
English language support

### ISSUE THREAD

**Issue by lordgabber** [swetorrentking/rartracker#7]
Hi!
Nice to see that tracker software alive and you working on improves and bug fixes and offcause about new fetures!
BTW any plans make it on english??
And may be more easy for config, not hardcoded!?

**Comment by swetorrentking** [comment]
Sometime this year I might do a i18n system for both back and front end with english as default and the ability to easy switch language.

Could you list areas you think are too hardcoded and I can focus on making them more configurable?

**Comment by lordgabber** [comment]
Better I waiting for i18n, when you realize it..
I love you tracker software and design, and waiting for english lang for start my own tracker!

**Comment by swetorrentking** [comment]
Glad to hear you would like to use it. And that makes me want to hurry up the translation process.

**Comment by lordgabber** [comment]
Mmm!  Yeah mate! It was great when you complete it!!
May be sometimes you also make admin panel? It was be very usefull.
But I remember times when i have BBS, and change some in config files, its also OK :dancer: 
Better make English version, Swedish is good, but i dont understand it :(

**Comment by swetorrentking** [comment]
What do you mean by admin panel? There is already an admin menu.

**Comment by 4play** [comment]
I also waitting English version. In any case, praise for this project.

**Comment by lordgabber** [comment]
I mean something like this: http://joxi.ru/n2YOKnGtj67Qwr
Where I can make/rename categories and many many.. SOme checkboxes e.t.c...

**Comment by swetorrentking** [comment]
I understand that you want to make more stuff more easier configurable. Right now you can do most of the things in your list, either via the visible admin-menu or manual in the code:

* Make/rename categories is in  app.config.js and probably also in some php-files like User.php
* MassPM. - Use the news-feature and check "flash" news and it will be like masspm
* Forums/Overforums - This is configured in the database, use phpMyAdmin or something. tables "forumheads", "forums".

Easier config for everything is of course good but everything takes time.

**Comment by Skruf90** [comment]
I will start making i18n implantation next week :)

**Comment by lordgabber** [comment]
WOW! Thats a amazing news!
Wating for this so much!!!

**Comment by 4play** [comment]
how's it going i18n implantation ?

**Comment by Skruf90** [comment]
Going good. Still under development. I'm about 60% done.

**Comment by lordgabber** [comment]
Very nice! Waiting for 100% :D

**Comment by lordgabber** [comment]
Hello King!
How its going with i18n? :dancer:

**Comment by 4play** [comment]
I hope that it will soon be finished this i18n

**Comment by lordgabber** [comment]
No news from King...
Last message was: "Going good. Still under development. I'm about 60% done." 17 days ago ;(
Hope all is going good!

**Comment by lordgabber** [comment]
Still in progress?

**Comment by lordgabber** [comment]
Hey King how is connect you directly? Your e-mail not working.

**Comment by swetorrentking** [comment]
lordgabber:
https://github.com/swetorrentking/rartracker/issues/12

**Comment by VENAXIS** [comment]
Would love to see the English language implemented in rartracker. Any updates?

**Comment by lordgabber** [comment]
No news dude a few months.

**Comment by VENAXIS** [comment]
@lordgabber Oh man... :(

**Comment by lordgabber** [comment]
Yep ;(
May be he need some help? ;D
Or more time? :D

**Comment by Skruf90** [comment]
I've been away on holiday. The i18n is all done. You can expect a pull request the upcoming week :)

**Comment by VENAXIS** [comment]
@Skruf90 Woo!

**Comment by 4play** [comment]
It can also be obtained custom support via skype ?

**Comment by lordgabber** [comment]
WOW! Nice news KING! You are the best!
Waiting for this new release! Also some demo will be available, to see how its looking??

p.s. im drop you a e-mail message, answer please.

**Comment by lordgabber** [comment]
And a swetorrentking and Skruf90 is one man? :D

**Comment by Skruf90** [comment]
I am not swetorrentking. I am a different person

**Comment by lordgabber** [comment]
But you make i18n? I.e. you and King in one development team?

**Comment by 4play** [comment]
@Skruf90 when will be able i18n ?

**Comment by lordgabber** [comment]
No news again!
Something going wrong with i18n! ;(

**Comment by maphex** [comment]
Waiting for the English translation also!

**Comment by swetorrentking** [comment]
I will begin multi language support with English primary language and hope it to be finished within a few weeks.

**Comment by lordgabber** [comment]
heh
===
Skruf90 commented on May 22
I've been away on holiday. The i18n is all done. You can expect a pull request the upcoming week :)
===

But anyway we continue waiting it :dancer: 
English is the best!

**Comment by swetorrentking** [comment]
That was 1 month ago. I am already half done with i18n now... it might be complete in a few days already, and I want to run a few days test to find possible errors.

**Comment by tinuva** [comment]
/Raises hand
Very willing to help with testing.

**Comment by lordgabber** [comment]
How can i help with testing?
Any demo access?

**Comment by swetorrentking** [comment]
Hehe, glad you want to help ;-)

I am 75% done now with the multilingual support. Just hold on a few days more and I think I can publish it here.

**Comment by lordgabber** [comment]
Can you install it on your demo server?
Then I can help with testing, but im from RU, and English not my native language ;)
And Im on IRC, see only Chaos online.. Its you? ;/

**Comment by swetorrentking** [comment]
After a few intensive days I have completed the multi language support with English and Swedish as default. I will publish the new version 0.3.0 of rartracker with this feature in the coming days after some testing and polish.

**Comment by lordgabber** [comment]
Super! We waiting this so long! 
Some another new features also comming in this 0.3.0 release?

**Comment by Jypels** [comment]
Can't wait for this, rartracker is definitely one of the best all in one solutions I have tested!

Please do let me know if you require any assistance with regards to testing or development.

**Comment by lordgabber** [comment]
Yes dude you right!
Rarat soft is the best!!!
