### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by Skruflix** [swetorrentking/rartracker#8]
Hi!

The whole /v1/api folder is missing. This is where login, signup, lost password is located y?
When building this folder and files is not generated. 

What to do ?

**Comment by swetorrentking** [comment]
It's not missing. You haven't got the url-rewrite to work.

1. Make sure to put the .htaccess in the www root
2. Activate rewrite engine with "a2enmod rewrite" or through the wamp-menu in windows
3. In httpd.conf ... change "AllowOverride None" to "AllowOverride All" under the <Directory, example: 
`<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
`

**Comment by Skruflix** [comment]
Yea, API functions works good now. 
The problem now is that when I try to login with the default account: 

System / password, is only says " Ett fel inträffade.". DB connection is correct.

**Comment by Skruflix** [comment]
I'm getting some error on the angular file when I check the chrome development console. When I do the bower install I get the option to choose from 5 different versions. Which version should I choose there?

**Comment by swetorrentking** [comment]
Just pick latest angular version 1.5.2
