### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by 4play** [swetorrentking/rartracker#9]
I following install guide bit i get back white (blank) page.

Server configiration

PHP Version 5.4.28-1~dotdeb.1
Apache/2.2.22 (Debian)
Loaded modules: core mod_log_config mod_logio mod_version prefork http_core mod_so mod_actions mod_alias mod_auth_basic mod_authn_file mod_authz_default mod_authz_groupfile mod_authz_host mod_authz_user mod_autoindex mod_cgi mod_deflate mod_dir mod_env mod_mime mod_negotiation mod_php5 mod_reqtimeout mod_rewrite mod_setenvif mod_ssl mod_status

Apache log say nothing usfully :/ any idea what is wrong?

**Comment by swetorrentking** [comment]
What about Chrome/Firefox developer tool logs? Are any XHR requests executed, and what are the response?
Do you get the index.html content when you view source? Do you have the 2 files in dist/  folder? Do you have the bower_components folder with its content?

**Comment by 4play** [comment]
I make some screens form developer tool (Safari)
http://saveotic.com/images/2016/03/29/4yTl9.png
http://saveotic.com/images/2016/03/29/MIk9K.png
http://saveotic.com/images/2016/03/29/qjUl.png
http://saveotic.com/images/2016/03/29/FVDMH.png

index.html was uploaded on the server
http://saveotic.com/images/2016/03/29/0IeWF.png

**Comment by swetorrentking** [comment]
Seems like something wrong with the webserver config or htaccess rewrites because all GET requests to external files just returns index.html ... try open **http://ADDRESS/dist/app-dist.js**  for example.

**Comment by 4play** [comment]
If i try open this link i get back white aka blank page

**Comment by swetorrentking** [comment]
That is the issue you need to look into. Why it doesn't load any files. It could be some error in the rewrite rule so every request returns index.html.

**Comment by 4play** [comment]
tnx for your time swetorrentking i hope to found someone who can with Debian
